# --------------------------- Default file paths ---------------------------- #
SAMPLE_MANIFEST: 'config/sample_manifest_all.tsv'

RESULTS_DIR: 'results'
FIGURE_DIR: 'results/figures'
QC_DIR: 'results/quality_control'

EXTERNAL_DATA_DIR: 'resources/external'
FASTQ_DIR: 'resources/fastq_seq'
GENOME_INDEX_DIR: 'resources/external/index'

LOG_DIR: 'logs'
TEMP_DIR: 'temp_data'
REPORT_DIR: 'reports'


# ---------------------------- Subset handles  ----------------------------- #


SUBSET_COLUMN: ''
SUBSET_VALUE: ''


# -------------------------- Specify tools to use -------------------------- #

ALIGNER: 'SALMON-TECOUNT' # options: 'HISAT2', 'SALMON-TXIMETA' or 'SALMON-TECOUNT' (warning: check necessary salmon args when using SALMON-TE)

# ----------------------- Params for raw processing ------------------------ #

TRIM_GALORE:
    QUALITY: 20
    EXTRA: ''

HISAT2:
    KM: 5
    EXTRA: '--no-mixed'

SAMTOOLS:
    MIN_MAPQ: 20

UNALIGNED_READS:
    HEAD_N: 15
    SUBSAMPLE_FRACT: 0.33


FEATURE_COUNTS:
    # COUNT_MODE: '--primary' #  --primary, −−fraction or -M
    FEATURE_TYPE: 'exon'
    ATTRIBUTE_TYPE: 'gene_id'
    EXTRA: ''

# -------------------- Params for downstream analysis ---------------------- #

ENSEMBL_VERSION: 108

LOW_READS_THRESHOLD: 10

DESEQ2:
    # MODEL
    DESIGN_FORMULA: '~ Sample_type + Treatment + Sample_type:Treatment'
    RELEVEL_COLUMNS: ['Sample_type', 'Treatment'] # warning: needs to be a vector
    SUBSET_COLUMN: ''
    SUBSET_VALUE: ''
    LOWREADS_THRESHOLD: 10
    # ANALYSIS
    FDR_THRESHOLD: 0.1 # (default 0.1)
    LOG2FC_THRESHOLD: 1
    PADJ_THRESHOLD: 0.05

CLUSTER_PROF:
    PADJ_THRESHOLD: 0.05
    MIN_GENESET_SIZE: 3
    MAX_GENESET_SIZE: 800

TE_COUNT:
    STRANDED: 'no' # options: no, forward, reverse  (default: no)
    MODE: 'multi' # options: uniq, multi  (default: multi)
    ITERATION: 100 # (default 100)
    EXTRA: ''